apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: default
spec:
  project: default
  source:
    repoURL: https://github.com/judexman01/my-nginx-app.git
    targetRevision: HEAD
    path: 
  destination:
    server: https://891F06C6B8C77B7A09572BA5B273BA53.sk1.us-east-1.eks.amazonaws.com
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
